version: "3.8"

services:
  odontocontrol_app:
    image: williamwilmer10/odontocontrol:latest
    networks:
      - wapainelnet
    command: >
      sh -c "node scripts/init-db.mjs && npx tsx scripts/bootstrap-super-admin.mjs && node .output/server/index.mjs"
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
      PORT: 3000

      APP_URL: https://odontocontrol.wapainel.com.br
      VITE_APP_URL: https://odontocontrol.wapainel.com.br

      DATABASE_URL: postgresql://odontocontrol:TROQUE_ESSA_SENHA_FORTE@odontocontrol_db:5432/odontocontrol
      DB_SSL: "false"

      BETTER_AUTH_SECRET: TROQUE_ESSE_SECRET_FORTE
      BETTER_AUTH_URL: https://odontocontrol.wapainel.com.br

      BOOTSTRAP_ADMIN_EMAIL: admin@admin.com
      BOOTSTRAP_ADMIN_PASSWORD: "@Admin.com"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.75"
          memory: 768M
        reservations:
          cpus: "0.10"
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.odontocontrol_app.rule=Host(`odontocontrol.wapainel.com.br`)
        - traefik.http.routers.odontocontrol_app.entrypoints=websecure
        - traefik.http.routers.odontocontrol_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.odontocontrol_app.service=odontocontrol_app
        - traefik.http.services.odontocontrol_app.loadbalancer.server.port=3000
        - traefik.http.services.odontocontrol_app.loadbalancer.passHostHeader=true

  odontocontrol_db:
    image: pgvector/pgvector:pg16
    networks:
      - wapainelnet
    environment:
      POSTGRES_DB: odontocontrol
      POSTGRES_USER: odontocontrol
      POSTGRES_PASSWORD: TROQUE_ESSA_SENHA_FORTE
      TZ: America/Sao_Paulo
    volumes:
      - odontocontrol_db_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.75"
          memory: 1024M
        reservations:
          cpus: "0.10"
          memory: 256M

volumes:
  odontocontrol_db_data:

networks:
  wapainelnet:
    external: true
