/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ClinicaSuspensaRouteImport } from './routes/clinica-suspensa'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterPainelRouteImport } from './routes/master/painel'
import { Route as MasterNovaClinicaRouteImport } from './routes/master/novaClinica'
import { Route as MasterListaClinicasRouteImport } from './routes/master/listaClinicas'
import { Route as MasterConfiguracoesRouteImport } from './routes/master/configuracoes'
import { Route as MasterClinicasSuspensasRouteImport } from './routes/master/clinicasSuspensas'
import { Route as DemoTratamentosRouteImport } from './routes/demo/Tratamentos'
import { Route as DemoRelatoriosRouteImport } from './routes/demo/Relatorios'
import { Route as DemoPacientesRouteImport } from './routes/demo/Pacientes'
import { Route as DemoOrcamentosRouteImport } from './routes/demo/Orcamentos'
import { Route as DemoFinanceiroRouteImport } from './routes/demo/Financeiro'
import { Route as DemoDashboardRouteImport } from './routes/demo/Dashboard'
import { Route as DemoAgendaRouteImport } from './routes/demo/Agenda'
import { Route as DemoAIGrowthRouteImport } from './routes/demo/AIGrowth'
import { Route as AppTratamentosRouteImport } from './routes/app/Tratamentos'
import { Route as AppRelatoriosRouteImport } from './routes/app/Relatorios'
import { Route as AppProfissionaisRouteImport } from './routes/app/Profissionais'
import { Route as AppProcedimentosRouteImport } from './routes/app/Procedimentos'
import { Route as AppPacientesRouteImport } from './routes/app/Pacientes'
import { Route as AppOrcamentosRouteImport } from './routes/app/Orcamentos'
import { Route as AppOnboardingRouteImport } from './routes/app/Onboarding'
import { Route as AppFinanceiroRouteImport } from './routes/app/Financeiro'
import { Route as AppEquipeRouteImport } from './routes/app/Equipe'
import { Route as AppDashboardRouteImport } from './routes/app/Dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app/Configuracoes'
import { Route as AppAgendaRouteImport } from './routes/app/Agenda'
import { Route as AppAIGrowthRouteImport } from './routes/app/AIGrowth'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaSuspensaRoute = ClinicaSuspensaRouteImport.update({
  id: '/clinica-suspensa',
  path: '/clinica-suspensa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovaClinicaRoute = MasterNovaClinicaRouteImport.update({
  id: '/novaClinica',
  path: '/novaClinica',
  getParentRoute: () => MasterRoute,
} as any)
const MasterListaClinicasRoute = MasterListaClinicasRouteImport.update({
  id: '/listaClinicas',
  path: '/listaClinicas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterClinicasSuspensasRoute = MasterClinicasSuspensasRouteImport.update({
  id: '/clinicasSuspensas',
  path: '/clinicasSuspensas',
  getParentRoute: () => MasterRoute,
} as any)
const DemoTratamentosRoute = DemoTratamentosRouteImport.update({
  id: '/Tratamentos',
  path: '/Tratamentos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRelatoriosRoute = DemoRelatoriosRouteImport.update({
  id: '/Relatorios',
  path: '/Relatorios',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPacientesRoute = DemoPacientesRouteImport.update({
  id: '/Pacientes',
  path: '/Pacientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOrcamentosRoute = DemoOrcamentosRouteImport.update({
  id: '/Orcamentos',
  path: '/Orcamentos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/Financeiro',
  path: '/Financeiro',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/Agenda',
  path: '/Agenda',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAIGrowthRoute = DemoAIGrowthRouteImport.update({
  id: '/AIGrowth',
  path: '/AIGrowth',
  getParentRoute: () => DemoRoute,
} as any)
const AppTratamentosRoute = AppTratamentosRouteImport.update({
  id: '/Tratamentos',
  path: '/Tratamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/Relatorios',
  path: '/Relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/Profissionais',
  path: '/Profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppProcedimentosRoute = AppProcedimentosRouteImport.update({
  id: '/Procedimentos',
  path: '/Procedimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/Pacientes',
  path: '/Pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/Orcamentos',
  path: '/Orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/Onboarding',
  path: '/Onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/Financeiro',
  path: '/Financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/Equipe',
  path: '/Equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/Configuracoes',
  path: '/Configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/Agenda',
  path: '/Agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAIGrowthRoute = AppAIGrowthRouteImport.update({
  id: '/AIGrowth',
  path: '/AIGrowth',
  getParentRoute: () => AppRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/clinica-suspensa': typeof ClinicaSuspensaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/AIGrowth': typeof AppAIGrowthRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracoes': typeof AppConfiguracoesRoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipe': typeof AppEquipeRoute
  '/app/Financeiro': typeof AppFinanceiroRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Orcamentos': typeof AppOrcamentosRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Procedimentos': typeof AppProcedimentosRoute
  '/app/Profissionais': typeof AppProfissionaisRoute
  '/app/Relatorios': typeof AppRelatoriosRoute
  '/app/Tratamentos': typeof AppTratamentosRoute
  '/demo/AIGrowth': typeof DemoAIGrowthRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financeiro': typeof DemoFinanceiroRoute
  '/demo/Orcamentos': typeof DemoOrcamentosRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Relatorios': typeof DemoRelatoriosRoute
  '/demo/Tratamentos': typeof DemoTratamentosRoute
  '/master/clinicasSuspensas': typeof MasterClinicasSuspensasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/novaClinica': typeof MasterNovaClinicaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/clinica-suspensa': typeof ClinicaSuspensaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/AIGrowth': typeof AppAIGrowthRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracoes': typeof AppConfiguracoesRoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipe': typeof AppEquipeRoute
  '/app/Financeiro': typeof AppFinanceiroRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Orcamentos': typeof AppOrcamentosRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Procedimentos': typeof AppProcedimentosRoute
  '/app/Profissionais': typeof AppProfissionaisRoute
  '/app/Relatorios': typeof AppRelatoriosRoute
  '/app/Tratamentos': typeof AppTratamentosRoute
  '/demo/AIGrowth': typeof DemoAIGrowthRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financeiro': typeof DemoFinanceiroRoute
  '/demo/Orcamentos': typeof DemoOrcamentosRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Relatorios': typeof DemoRelatoriosRoute
  '/demo/Tratamentos': typeof DemoTratamentosRoute
  '/master/clinicasSuspensas': typeof MasterClinicasSuspensasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/novaClinica': typeof MasterNovaClinicaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/clinica-suspensa': typeof ClinicaSuspensaRoute
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/AIGrowth': typeof AppAIGrowthRoute
  '/app/Agenda': typeof AppAgendaRoute
  '/app/Configuracoes': typeof AppConfiguracoesRoute
  '/app/Dashboard': typeof AppDashboardRoute
  '/app/Equipe': typeof AppEquipeRoute
  '/app/Financeiro': typeof AppFinanceiroRoute
  '/app/Onboarding': typeof AppOnboardingRoute
  '/app/Orcamentos': typeof AppOrcamentosRoute
  '/app/Pacientes': typeof AppPacientesRoute
  '/app/Procedimentos': typeof AppProcedimentosRoute
  '/app/Profissionais': typeof AppProfissionaisRoute
  '/app/Relatorios': typeof AppRelatoriosRoute
  '/app/Tratamentos': typeof AppTratamentosRoute
  '/demo/AIGrowth': typeof DemoAIGrowthRoute
  '/demo/Agenda': typeof DemoAgendaRoute
  '/demo/Dashboard': typeof DemoDashboardRoute
  '/demo/Financeiro': typeof DemoFinanceiroRoute
  '/demo/Orcamentos': typeof DemoOrcamentosRoute
  '/demo/Pacientes': typeof DemoPacientesRoute
  '/demo/Relatorios': typeof DemoRelatoriosRoute
  '/demo/Tratamentos': typeof DemoTratamentosRoute
  '/master/clinicasSuspensas': typeof MasterClinicasSuspensasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaClinicas': typeof MasterListaClinicasRoute
  '/master/novaClinica': typeof MasterNovaClinicaRoute
  '/master/painel': typeof MasterPainelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/clinica-suspensa'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/AIGrowth'
    | '/app/Agenda'
    | '/app/Configuracoes'
    | '/app/Dashboard'
    | '/app/Equipe'
    | '/app/Financeiro'
    | '/app/Onboarding'
    | '/app/Orcamentos'
    | '/app/Pacientes'
    | '/app/Procedimentos'
    | '/app/Profissionais'
    | '/app/Relatorios'
    | '/app/Tratamentos'
    | '/demo/AIGrowth'
    | '/demo/Agenda'
    | '/demo/Dashboard'
    | '/demo/Financeiro'
    | '/demo/Orcamentos'
    | '/demo/Pacientes'
    | '/demo/Relatorios'
    | '/demo/Tratamentos'
    | '/master/clinicasSuspensas'
    | '/master/configuracoes'
    | '/master/listaClinicas'
    | '/master/novaClinica'
    | '/master/painel'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/clinica-suspensa'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/AIGrowth'
    | '/app/Agenda'
    | '/app/Configuracoes'
    | '/app/Dashboard'
    | '/app/Equipe'
    | '/app/Financeiro'
    | '/app/Onboarding'
    | '/app/Orcamentos'
    | '/app/Pacientes'
    | '/app/Procedimentos'
    | '/app/Profissionais'
    | '/app/Relatorios'
    | '/app/Tratamentos'
    | '/demo/AIGrowth'
    | '/demo/Agenda'
    | '/demo/Dashboard'
    | '/demo/Financeiro'
    | '/demo/Orcamentos'
    | '/demo/Pacientes'
    | '/demo/Relatorios'
    | '/demo/Tratamentos'
    | '/master/clinicasSuspensas'
    | '/master/configuracoes'
    | '/master/listaClinicas'
    | '/master/novaClinica'
    | '/master/painel'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/clinica-suspensa'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/AIGrowth'
    | '/app/Agenda'
    | '/app/Configuracoes'
    | '/app/Dashboard'
    | '/app/Equipe'
    | '/app/Financeiro'
    | '/app/Onboarding'
    | '/app/Orcamentos'
    | '/app/Pacientes'
    | '/app/Procedimentos'
    | '/app/Profissionais'
    | '/app/Relatorios'
    | '/app/Tratamentos'
    | '/demo/AIGrowth'
    | '/demo/Agenda'
    | '/demo/Dashboard'
    | '/demo/Financeiro'
    | '/demo/Orcamentos'
    | '/demo/Pacientes'
    | '/demo/Relatorios'
    | '/demo/Tratamentos'
    | '/master/clinicasSuspensas'
    | '/master/configuracoes'
    | '/master/listaClinicas'
    | '/master/novaClinica'
    | '/master/painel'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClinicaSuspensaRoute: typeof ClinicaSuspensaRoute
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica-suspensa': {
      id: '/clinica-suspensa'
      path: '/clinica-suspensa'
      fullPath: '/clinica-suspensa'
      preLoaderRoute: typeof ClinicaSuspensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/novaClinica': {
      id: '/master/novaClinica'
      path: '/novaClinica'
      fullPath: '/master/novaClinica'
      preLoaderRoute: typeof MasterNovaClinicaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/listaClinicas': {
      id: '/master/listaClinicas'
      path: '/listaClinicas'
      fullPath: '/master/listaClinicas'
      preLoaderRoute: typeof MasterListaClinicasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/clinicasSuspensas': {
      id: '/master/clinicasSuspensas'
      path: '/clinicasSuspensas'
      fullPath: '/master/clinicasSuspensas'
      preLoaderRoute: typeof MasterClinicasSuspensasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/demo/Tratamentos': {
      id: '/demo/Tratamentos'
      path: '/Tratamentos'
      fullPath: '/demo/Tratamentos'
      preLoaderRoute: typeof DemoTratamentosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Relatorios': {
      id: '/demo/Relatorios'
      path: '/Relatorios'
      fullPath: '/demo/Relatorios'
      preLoaderRoute: typeof DemoRelatoriosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Pacientes': {
      id: '/demo/Pacientes'
      path: '/Pacientes'
      fullPath: '/demo/Pacientes'
      preLoaderRoute: typeof DemoPacientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Orcamentos': {
      id: '/demo/Orcamentos'
      path: '/Orcamentos'
      fullPath: '/demo/Orcamentos'
      preLoaderRoute: typeof DemoOrcamentosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Financeiro': {
      id: '/demo/Financeiro'
      path: '/Financeiro'
      fullPath: '/demo/Financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Dashboard': {
      id: '/demo/Dashboard'
      path: '/Dashboard'
      fullPath: '/demo/Dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/Agenda': {
      id: '/demo/Agenda'
      path: '/Agenda'
      fullPath: '/demo/Agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/AIGrowth': {
      id: '/demo/AIGrowth'
      path: '/AIGrowth'
      fullPath: '/demo/AIGrowth'
      preLoaderRoute: typeof DemoAIGrowthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/app/Tratamentos': {
      id: '/app/Tratamentos'
      path: '/Tratamentos'
      fullPath: '/app/Tratamentos'
      preLoaderRoute: typeof AppTratamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Relatorios': {
      id: '/app/Relatorios'
      path: '/Relatorios'
      fullPath: '/app/Relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Profissionais': {
      id: '/app/Profissionais'
      path: '/Profissionais'
      fullPath: '/app/Profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Procedimentos': {
      id: '/app/Procedimentos'
      path: '/Procedimentos'
      fullPath: '/app/Procedimentos'
      preLoaderRoute: typeof AppProcedimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Pacientes': {
      id: '/app/Pacientes'
      path: '/Pacientes'
      fullPath: '/app/Pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Orcamentos': {
      id: '/app/Orcamentos'
      path: '/Orcamentos'
      fullPath: '/app/Orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Onboarding': {
      id: '/app/Onboarding'
      path: '/Onboarding'
      fullPath: '/app/Onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Financeiro': {
      id: '/app/Financeiro'
      path: '/Financeiro'
      fullPath: '/app/Financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Equipe': {
      id: '/app/Equipe'
      path: '/Equipe'
      fullPath: '/app/Equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Dashboard': {
      id: '/app/Dashboard'
      path: '/Dashboard'
      fullPath: '/app/Dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Configuracoes': {
      id: '/app/Configuracoes'
      path: '/Configuracoes'
      fullPath: '/app/Configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/Agenda': {
      id: '/app/Agenda'
      path: '/Agenda'
      fullPath: '/app/Agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/AIGrowth': {
      id: '/app/AIGrowth'
      path: '/AIGrowth'
      fullPath: '/app/AIGrowth'
      preLoaderRoute: typeof AppAIGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAIGrowthRoute: typeof AppAIGrowthRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProcedimentosRoute: typeof AppProcedimentosRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTratamentosRoute: typeof AppTratamentosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAIGrowthRoute: AppAIGrowthRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProcedimentosRoute: AppProcedimentosRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTratamentosRoute: AppTratamentosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAIGrowthRoute: typeof DemoAIGrowthRoute
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoOrcamentosRoute: typeof DemoOrcamentosRoute
  DemoPacientesRoute: typeof DemoPacientesRoute
  DemoRelatoriosRoute: typeof DemoRelatoriosRoute
  DemoTratamentosRoute: typeof DemoTratamentosRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAIGrowthRoute: DemoAIGrowthRoute,
  DemoAgendaRoute: DemoAgendaRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoOrcamentosRoute: DemoOrcamentosRoute,
  DemoPacientesRoute: DemoPacientesRoute,
  DemoRelatoriosRoute: DemoRelatoriosRoute,
  DemoTratamentosRoute: DemoTratamentosRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterClinicasSuspensasRoute: typeof MasterClinicasSuspensasRoute
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterListaClinicasRoute: typeof MasterListaClinicasRoute
  MasterNovaClinicaRoute: typeof MasterNovaClinicaRoute
  MasterPainelRoute: typeof MasterPainelRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterClinicasSuspensasRoute: MasterClinicasSuspensasRoute,
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterListaClinicasRoute: MasterListaClinicasRoute,
  MasterNovaClinicaRoute: MasterNovaClinicaRoute,
  MasterPainelRoute: MasterPainelRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClinicaSuspensaRoute: ClinicaSuspensaRoute,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
